import os
import io
import duckdb
import pandas as pd
from minio import Minio
from dotenv import load_dotenv

# Load configuration
load_dotenv()

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "127.0.0.1:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "minioadmin")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "minioadmin")
host_endpoint = MINIO_ENDPOINT.replace("http://", "").replace("https://", "")

# Initialize MinIO Client
minio_client = Minio(
    host_endpoint,
    access_key=MINIO_ACCESS_KEY,
    secret_key=MINIO_SECRET_KEY,
    secure=False
)

BUCKET_NAME = "data"
SILVER_PREFIX = "silver/"
GOLD_PREFIX = "gold/"

def upload_gold_parquet(local_file_path, filename):
    """Helper to upload a Gold asset file directly to MinIO from a disk block location."""
    try:
        minio_path = f"{GOLD_PREFIX}{filename}"
        minio_client.fput_object(BUCKET_NAME, minio_path, local_file_path)
        print(f"✨ [GOLD LAYER] Saved aggregated asset to: {BUCKET_NAME}/{minio_path}")
        
        # Clean up local temp file
        if os.path.exists(local_file_path):
            os.remove(local_file_path)
    except Exception as e:
        print(f"❌ Failed to write Gold asset {filename} to MinIO: {e}")

def register_silver_view(con, dataset_name):
    """
    Locates the direct clean parquet file generated by the silver step
    and registers it as a fast virtual view inside the DuckDB environment.
    """
    clean_filename = f"{dataset_name}_clean.parquet"
    minio_blob_path = f"{SILVER_PREFIX}{dataset_name}/{clean_filename}"
    local_temp_path = os.path.join(os.getcwd(), f"temp_{clean_filename}")
    
    try:
        minio_client.fget_object(BUCKET_NAME, minio_blob_path, local_temp_path)
        con.execute(f"CREATE OR REPLACE VIEW view_{dataset_name} AS SELECT * FROM read_parquet('{local_temp_path}')")
        return local_temp_path
    except Exception as e:
        print(f"⚠️ Could not load silver dataset view for '{dataset_name}': {e}")
        return None

def build_gold_layer():
    print("🚀 Registering Silver Tables for Gold Insights Processing...")
    
    con = duckdb.connect(database=':memory:')
    tracked_files = []
    
    f1 = register_silver_view(con, "individual_contributions")
    f2 = register_silver_view(con, "committee_contributions_to_candidates")
    f3 = register_silver_view(con, "independent_expenditures")
    
    if f1: tracked_files.append(f1)
    if f2: tracked_files.append(f2)
    if f3: tracked_files.append(f3)

    registered_views = [v[0] for v in con.execute("SELECT view_name FROM duckdb_views()").fetchall()]

    # -------------------------------------------------------------------------
    # ANALYSIS 1: NETWORK EDGES & CENTRALITY (Political Cash Flow Graph)
    # -------------------------------------------------------------------------
    print("\n🕸️ Modeling political transaction network edges via DuckDB...")
    
    edge_queries = []
    
    if "view_individual_contributions" in registered_views:
        cols = [c[1] for c in con.execute("PRAGMA table_info('view_individual_contributions')").fetchall()]
        s = "contrib_name" if "contrib_name" in cols else "CAST('UNKNOWN' AS VARCHAR)"
        t = "com_id" if "com_id" in cols else "CAST('UNKNOWN' AS VARCHAR)"
        
        edge_queries.append(f"""
            SELECT {s} AS source, {t} AS target, SUM(trans_amt) AS weight, COUNT(trans_amt) AS transaction_count, 'individual_to_committee' AS edge_type
            FROM view_individual_contributions 
            WHERE trans_amt > 0
            GROUP BY 1, 2
        """)
        
    if "view_committee_contributions_to_candidates" in registered_views:
        cols = [c[1] for c in con.execute("PRAGMA table_info('view_committee_contributions_to_candidates')").fetchall()]
        s = "com_id" if "com_id" in cols else "CAST('UNKNOWN' AS VARCHAR)"
        t = "cand_id" if "cand_id" in cols else ("other_com_id" if "other_com_id" in cols else "CAST('UNKNOWN' AS VARCHAR)")
        
        edge_queries.append(f"""
            SELECT {s} AS source, {t} AS target, SUM(trans_amt) AS weight, COUNT(trans_amt) AS transaction_count, 'committee_to_candidate' AS edge_type
            FROM view_committee_contributions_to_candidates
            WHERE trans_amt > 0
            GROUP BY 1, 2
        """)
        
    if "view_independent_expenditures" in registered_views:
        cols = [c[1] for c in con.execute("PRAGMA table_info('view_independent_expenditures')").fetchall()]
        s = "com_id" if "com_id" in cols else "CAST('UNKNOWN' AS VARCHAR)"
        t = "cand_id" if "cand_id" in cols else ("other_com_id" if "other_com_id" in cols else "CAST('UNKNOWN' AS VARCHAR)")
        
        edge_queries.append(f"""
            SELECT {s} AS source, {t} AS target, SUM(trans_amt) AS weight, COUNT(trans_amt) AS transaction_count, 'independent_expenditure' AS edge_type
            FROM view_independent_expenditures
            WHERE trans_amt > 0
            GROUP BY 1, 2
        """)

    if edge_queries:
        union_edges_sql = " UNION ALL ".join(edge_queries)
        con.execute(f"CREATE OR REPLACE VIEW combined_edges AS {union_edges_sql}")
        
        local_edges_path = os.path.join(os.getcwd(), "gold_network_edges.parquet")
        con.execute(f"COPY (SELECT * FROM combined_edges) TO '{local_edges_path}' (FORMAT PARQUET, COMPRESSION 'SNAPPY')")
        upload_gold_parquet(local_edges_path, "network_edges.parquet")
        
        print("📊 Computing node-level out-degrees and in-degrees in parallel...")
        con.execute("""
            CREATE OR REPLACE VIEW node_centrality AS
            WITH out_degree AS (
                SELECT source AS node_id, SUM(weight) AS total_outflow FROM combined_edges GROUP BY source
            ),
            in_degree AS (
                SELECT target AS node_id, SUM(weight) AS total_inflow FROM combined_edges GROUP BY target
            )
            SELECT 
                COALESCE(o.node_id, i.node_id) AS node_id,
                COALESCE(o.total_outflow, 0.0) AS total_outflow,
                COALESCE(i.total_inflow, 0.0) AS total_inflow
            FROM out_degree o 
            FULL OUTER JOIN in_degree i ON o.node_id = i.node_id
        """)
        
        local_nodes_path = os.path.join(os.getcwd(), "gold_network_nodes.parquet")
        con.execute(f"COPY (SELECT * FROM node_centrality) TO '{local_nodes_path}' (FORMAT PARQUET, COMPRESSION 'SNAPPY')")
        upload_gold_parquet(local_nodes_path, "network_nodes_centrality.parquet")
    else:
        print("⚠️ No valid source tables found to map network graph structures.")

    # -------------------------------------------------------------------------
    # ANALYSIS 2: TEMPORAL SURGES & VELOCITY (Anomalous Spending Spikes)
    # -------------------------------------------------------------------------
    print("\n⏱️ Analyzing money velocity & windowed temporal spending surges...")
    if "view_independent_expenditures" in registered_views:
        cols = [c[1] for c in con.execute("PRAGMA table_info('view_independent_expenditures')").fetchall()]
        if "com_id" in cols and "trans_date" in cols and "trans_amt" in cols:
            con.execute("""
                CREATE OR REPLACE VIEW velocity_stage1 AS
                SELECT 
                    com_id,
                    CAST(trans_date AS DATE) AS trans_date,
                    SUM(trans_amt) AS daily_amt
                FROM view_independent_expenditures
                WHERE trans_date IS NOT NULL AND trans_date != ''
                GROUP BY com_id, trans_date
            """)
            
            con.execute("""
                CREATE OR REPLACE VIEW velocity_stage2 AS
                SELECT 
                    com_id,
                    strftime(trans_date, '%Y-%m-%d') AS trans_date,
                    daily_amt AS trans_amt,
                    AVG(daily_amt) OVER(PARTITION BY com_id ORDER BY trans_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7d_avg,
                    STDDEV_SAMP(daily_amt) OVER(PARTITION BY com_id ORDER BY trans_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7d_std
                FROM velocity_stage1
            """)
            
            local_velocity_path = os.path.join(os.getcwd(), "gold_velocity.parquet")
            con.execute(f"""
                COPY (
                    SELECT 
                        com_id, trans_date, trans_amt, rolling_7d_avg, COALESCE(rolling_7d_std, 0.0) AS rolling_7d_std,
                        CASE WHEN trans_amt > (rolling_7d_avg + (2.5 * COALESCE(rolling_7d_std, 0.0))) THEN 1 ELSE 0 END AS velocity_anomaly_flag
                    FROM velocity_stage2
                ) TO '{local_velocity_path}' (FORMAT PARQUET, COMPRESSION 'SNAPPY')
            """)
            upload_gold_parquet(local_velocity_path, "temporal_spending_velocity.parquet")
        else:
            print("⚠️ view_independent_expenditures is missing columns required for velocity tracking.")
    else:
        print("⚠️ Expenditure dataset missing. Skipping temporal velocity analysis.")

    # -------------------------------------------------------------------------
    # ANALYSIS 3: DONOR COALITIONS / CONCENTRATION BY BUSINESS SECTOR
    # -------------------------------------------------------------------------
    print("\n🏢 Mapping donor networks and institutional employer groupings...")
    if "view_individual_contributions" in registered_views:
        cols = [c[1] for c in con.execute("PRAGMA table_info('view_individual_contributions')").fetchall()]
        if "com_id" in cols and "trans_amt" in cols:
            emp_field = "contrib_emp" if "contrib_emp" in cols else "CAST('UNKNOWN' AS VARCHAR)"
            name_field = "contrib_name" if "contrib_name" in cols else "CAST('UNKNOWN' AS VARCHAR)"
            
            local_donor_path = os.path.join(os.getcwd(), "gold_donor_concentration.parquet")
            con.execute(f"""
                COPY (
                    SELECT 
                        {emp_field} AS contrib_emp,
                        com_id,
                        SUM(trans_amt) AS total_funding,
                        COUNT(DISTINCT {name_field}) AS distinct_donors
                    FROM view_individual_contributions
                    GROUP BY 1, 2
                    HAVING SUM(trans_amt) >= 5000
                    ORDER BY total_funding DESC
                ) TO '{local_donor_path}' (FORMAT PARQUET, COMPRESSION 'SNAPPY')
            """)
            upload_gold_parquet(local_donor_path, "donor_concentration_by_sector.parquet")
        else:
            print("⚠️ view_individual_contributions is missing core tracking columns. Skipping sector summary.")
    else:
        print("⚠️ Individual contributions dataset missing. Skipping sector summary aggregation.")

    # Clean up local temporary silver files scanned by the query engine
    print("\n🧹 Discarding temporary query staging structures...")
    for f in tracked_files:
        if os.path.exists(f):
            os.remove(f)

    print("🏁 Gold Layer Engine processing successfully concluded.")

if __name__ == "__main__":
    build_gold_layer()